name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    container: rust:1.59
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose

  test:
    runs-on: ubuntu-latest
    container: xd009642/tarpaulin:0.20.0
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run tests
      run: cargo tarpaulin --verbose --ciserver github-ci --coveralls $COVERALLS_REPO_TOKEN
